# Configuration for netlify previews of the pages.
[build]
  base = "."
  publish = ".builds/web/"
  command = "npm run build:prod"

[[redirects]]
  from = "/"
  to = "/pages/onboarding.html"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "https://welearn.cri-paris.org/api/:splat"
  status = 200

[[redirects]]
  from = "/meta/*"
  to = "https://welearn.cri-paris.org/meta/:splat"
  status = 200
