# Configuration for netlify previews of the pages.
[build]
  base = "."
  publish = ".builds/web/"
  command = "npm run build:prod"

[[redirects]]
  from = "/"
  to = "/pages/onboarding.html"
  status = 301
  force = false
